starting-hearts: 10
min-hearts: 0
max-hearts: 20

# Heart gain/loss
hearts-gained-per-kill: 1
hearts-lost-per-death: 1
natural-death-loss: true

# PvP/PvE cycle
pvp-cycle:
  enabled: true
  pvp-duration: 2
  pve-duration: 2
  on-switch:
    - "broadcast &cSwitched to &4%mode% &cmode!"
    - "playsound entity.ender_dragon.growl @a"

# Bounty System
bounty:
  enabled: true
  min-players: 10
  location-broadcast-interval: 5  # In minutes
  reward-hearts: 1
  logout-penalty:
    enabled: true
    hearts-lost: 2
  messages:
    start: "&c&lBOUNTY! &fA bounty has been placed on &c%player%&f! Hunt them down for a reward!"
    rare-start: "&c&l⚠ RARE BOUNTY! &6&lA rare bounty has been placed on &c%player%&6&l! Hunt them down for a special reward!"
    location: "&c&lBOUNTY LOCATION! &f%player% is at &c%x%, %y%, %z% &fin &c%world%"
    killed: "&c&lBOUNTY CLAIMED! &f%killer% has killed %player% and claimed the bounty!"
    rare-killed: "&c&l⚠ RARE BOUNTY CLAIMED! &6&l%killer% has killed %player% and claimed the rare bounty! They received a Revival Heart!"
    survived: "&c&lBOUNTY SURVIVED! &f%player% has survived the bounty and earned a heart!"
    rare-survived: "&c&l⚠ RARE BOUNTY SURVIVED! &6&l%player% has survived the rare bounty and earned extra hearts and a Revival Heart!"
    not-enough-players: "&c&lBOUNTY SYSTEM! &fNot enough players online for bounty system to activate."
    logout-penalty: "&c&lBOUNTY ESCAPED! &f%player% has left the server while having a bounty and lost %hearts% hearts!"

# Boss Bar Configuration
boss-bar:
  enabled: true
  messages:
    - text: "&6&lYourserver.com"
      duration: "30s"
    - text: "&a&lLifeSteal"
      duration: "30s"
    - text: "&e&lby akar1881"
      duration: "30s"
    - text: "&b&lSeason 1"
      duration: "30s"
# additional messages can be added here
  # The boss bar will cycle through these messages every 30 seconds
  # up to 10 messages can be added

# Action bar timer display
action-bar:
  enabled: true
  format-pvp: "&cPVP &f\\ &e%time%"
  format-pve: "&aPVE &f\\ &e%time%"

# What happens when a player reaches 0 hearts
elimination:
  mode: "spectator"  # Options: "ban", "spectator"
  command: "say %player% has been eliminated from LifeSteal!"

# Sounds and messages
sounds:
  heart-gain: "entity.player.levelup"
  heart-loss: "entity.player.hurt"

messages:
  heart-gain: "&aYou gained a heart!"
  heart-loss: "&cYou lost a heart!"
  banned: "&4You have been eliminated!"