starting-hearts: 10
min-hearts: 0
max-hearts: 20

# Heart gain/loss
hearts-gained-per-kill: 1
hearts-lost-per-death: 1
natural-death-loss: false

# PvP/PvE cycle
pvp-cycle:
  enabled: true
  pvp-duration: 2
  pve-duration: 2
  on-switch:
    - "broadcast &cSwitched to &4%mode% &cmode!"
    - "playsound entity.ender_dragon.growl @a"

# Action bar timer display
action-bar:
  enabled: true
  format-pvp: "&cPVP &f\\ &e%time%"
  format-pve: "&aPVE &f\\ &e%time%"

# What happens when a player reaches 0 hearts
elimination:
  mode: "spectator"  # Options: "ban", "spectator"
  command: "say %player% has been eliminated from LifeSteal!"

# Sounds and messages
sounds:
  heart-gain: "entity.player.levelup"
  heart-loss: "entity.player.hurt"

messages:
  heart-gain: "&aYou gained a heart!"
  heart-loss: "&cYou lost a heart!"
  banned: "&4You have been eliminated!"