starting-hearts: 10
min-hearts: 0
max-hearts: 20

# Heart gain/loss
hearts-gained-per-kill: 1
hearts-lost-per-death: 1
natural-death-loss: true

# sTorage configuration
storage:
  type: sqlite # Storage type: 'mysql' or 'sqlite'
  # MYSQL Configuration
  # Uncomment the following lines to use MySQL instead of SQLite
  # Make sure to configure your MySQL settings below
  mysql:
    host: localhost
    port: 3306
    database: lifesteal
    user: root
    password: password
  # SQLite Configuration
  # Uncomment the following lines to use SQLite
  # Make sure to configure your SQLite settings below
  # SQLite is used by default, so you can leave this as is
  sqlite:
    file: plugins/Lifesteal/storage/lifesteal.db


# First Join System
first-join:
  enabled: true
  messages:
    - "&6Welcome to our LifeSteal SMP!"
    - "&eThis is a hardcore survival experience where:"
    - "&c- You lose hearts when you die"
    - "&a- You gain hearts by killing other players"
    - "&e- Players with 0 hearts are eliminated"
    - "&6Type &lCONFIRM &6in chat if you agree to these rules"
  confirm-message: "&aCongratulations! Welcome to the server!"
  teleport-message: "&aYou have been teleported to a safe location. Good luck!"
  reconnect-kick-message: "&aPlease reconnect for optimal performance"
  kick-after-teleport: false  # Set to true to kick players after teleporting them to a safe location
  queue-music: true  # Play music discs in the queue world

# Safe Location Finder
safe-location:
  min-distance: 700  # Minimum distance from spawn (in blocks)
  max-distance: 1300  # Maximum distance from spawn (in blocks)
  max-attempts: 20   # Maximum number of attempts to find a safe location

# Chunk Pre-generation (requires Chunky plugin)
chunk-pregeneration:
  enabled: true  # Enable chunk pre-generation
  radius: 8000   # Radius in blocks to pre-generate (will use world border size if world border is enabled)

# World Border System
world-border:
  enabled: true
  worlds:
    - "world"  # Only apply to the overworld by default
  initial-size: 5000  # Initial border size in blocks (diameter) - good for 50+ players - good for 50+ players
  center:
    use-world-spawn: true  # If true, uses the world spawn point as center
    x: 0  # Only used if use-world-spawn is false
    z: 0  # Only used if use-world-spawn is false
  shrink:
    enabled: false
    interval: 30  # Time in minutes between each shrink
    amount: 100   # Amount to shrink by each time (in blocks)
    min-size: 500  # Minimum size the border can shrink to
    warning-time: 60  # Time in seconds to warn players before shrink
    warning-distance: 50  # Distance in blocks to warn players
  damage:
    amount: 1.0  # Damage per second when outside border
    buffer: 5.0  # Buffer zone in blocks
  messages:
    border-shrinking: "&c&lWARNING! &fThe world border is shrinking in &e%time% &fseconds!"
    border-shrunk: "&c&lBORDER SHRUNK! &fThe world border has shrunk to &e%size% &fblocks!"
    outside-border: "&c&lWARNING! &fYou are outside the world border! Return immediately or take damage!"

# PvP/PvE cycle
pvp-cycle:
  enabled: true
  pvp-duration: 2
  pve-duration: 2
  on-switch:
    - "broadcast &cSwitched to &4%mode% &cmode!"
    - "playsound entity.ender_dragon.growl @a"

# Bounty System
bounty:
  enabled: true
  min-players: 10
  location-broadcast-interval: 5  # In minutes
  reward-hearts: 1
  logout-penalty:
    enabled: true
    hearts-lost: 2
  messages:
    start: "&c&lBOUNTY! &fA bounty has been placed on &c%player%&f! Hunt them down for a reward!"
    rare-start: "&c&l⚠ RARE BOUNTY! &6&lA rare bounty has been placed on &c%player%&6&l! Hunt them down for a special reward!"
    location: "&c&lBOUNTY LOCATION! &f%player% is at &c%x%, %y%, %z% &fin &c%world%"
    killed: "&c&lBOUNTY CLAIMED! &f%killer% has killed %player% and claimed the bounty!"
    rare-killed: "&c&l⚠ RARE BOUNTY CLAIMED! &6&l%killer% has killed %player% and claimed the rare bounty! They received a Revival Heart!"
    survived: "&c&lBOUNTY SURVIVED! &f%player% has survived the bounty and earned a heart!"
    rare-survived: "&c&l⚠ RARE BOUNTY SURVIVED! &6&l%player% has survived the rare bounty and earned extra hearts and a Revival Heart!"
    not-enough-players: "&c&lBOUNTY SYSTEM! &fNot enough players online for bounty system to activate."
    logout-penalty: "&c&lBOUNTY ESCAPED! &f%player% has left the server while having a bounty and lost %hearts% hearts!"

# Boss Bar Configuration
boss-bar:
  enabled: true
  messages:
    - text: "&6&lYourserver.com"
      duration: "30s"
    - text: "&a&lLifeSteal"
      duration: "30s"
    - text: "&e&lby akar1881"
      duration: "30s"
    - text: "&b&lSeason 1"
      duration: "30s"
# additional messages can be added here
  # The boss bar will cycle through these messages every 30 seconds
  # up to 10 messages can be added

# Action bar timer display
action-bar:
  enabled: true
  format-pvp: "&cPVP &f\\ &e%time%"
  format-pve: "&aPVE &f\\ &e%time%"

# What happens when a player reaches 0 hearts
elimination:
  mode: "spectator"  # Options: "ban", "spectator"
  command: "say %player% has been eliminated from LifeSteal!"

# Sounds and messages
sounds:
  heart-gain: "entity.player.levelup"
  heart-loss: "entity.player.hurt"

messages:
  heart-gain: "&aYou gained a heart!"
  heart-loss: "&cYou lost a heart!"
  banned: "&4You have been eliminated!"