name: LifeSteal
version: '1.1-RELEASE'
main: com.lifesteal.LifeSteal
api-version: '1.17'
commands:
  lifesteal:
    description: Main command for LifeSteal plugin
    usage: /<command> [reload|hearts|revive|schedule|togglebar]
    aliases: [ls]
  ally:
    description: Manage your allies
    usage: /<command> [player|list|accept|deny]
permissions:
  lifesteal.admin:
    description: Gives access to all LifeSteal admin commands
    default: op
  lifesteal.item.use.heart:
    description: Allows using heart items
    default: true
  lifesteal.item.use.revive:
    description: Allows using revive items
    default: true
  lifesteal.bypass.maxhearts:
    description: Bypasses the maximum hearts limit
    default: op